apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
spec:
  type: LoadBalancer
  selector:
    app: ml-app
  ports:
    - protocol: TCP
      port: 80         # this is the port people will hit
      targetPort: 8080 # port inside the pod
# external port to hit from VM / browser
