apiVersion: v1
kind: Service
metadata:
  name: ml-app-service
spec:
  type: NodePort
  selector:
    app: ml-app
  ports:
    - protocol: TCP
      port: 8080       # port inside the pod
      targetPort: 8080 # container port
      nodePort: 30080  # external port to hit from VM / browser
