name: Weekly Data Ingestion

permissions:
  contents: write
  actions: write  

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * SUN"   # edit to desired schedule (UTC)

jobs:
  ingest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
          # Install pydantic first (needed by FastAPI)
          pip install pydantic==1.10.15

          # Install DVC first (so dependency conflict doesn’t break it)
          pip install "dvc[gs]" --no-cache-dir
      
          # 1️⃣ Install Evidently WITHOUT any dependencies
          pip install evidently==0.7.3 --no-deps
      
          # 2️⃣ Install Evidently dependencies manually (ALL except pydantic)
          pip install ujson nltk deprecation typing-inspect uuid6 numpy pandas scipy requests PyYAML jinja2 matplotlib plotly
      
          # 3️⃣ Install YOUR requirements file
          # Ignore Evidently from requirements.txt to avoid reinstalling with deps
          sed '/evidently/d' requirements.txt > req-clean.txt
          pip install -r req-clean.txt --no-cache-dir

      - name: Configure GCP auth
        env:
          GCP_B64: ${{ secrets.GCP_CREDENTIALS_B64 }}
        run: |
          echo "$GCP_B64" | base64 -d > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV

      - name: Download latest batch from GCS
        run: |
          mkdir -p data/new_batch
          gsutil cp gs://heart-disease-mlops-data/new_batches/latest_batch.csv data/new_batch/new_batch.csv || exit 0
          ls -la data/new_batch

      - name: Install GitHub CLI
        run: sudo apt-get install gh -y

      # - name: Drift check on new batch
      #   run: python scripts/drift_check.py --mode ingest --batch data/new_batch/new_batch.csv  


      # - name: Trigger retrain on drift
      #   if: steps.drift_check.outcome == 'failure'
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     echo "Drift detected - triggering retrain.yml..."
      #     gh workflow run retrain.yml --ref main
      - name: Drift check on new batch
        id: drift_check
        run: |
          python scripts/drift_check.py --mode ingest --batch data/new_batch/new_batch.csv
          echo "exit_code=$?" >> $GITHUB_OUTPUT
      
      - name: Trigger retrain on drift
        if: steps.drift_check.outputs.exit_code != '0'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Drift detected - triggering retrain..."
          gh workflow run retrain.yml --ref main
      
