name: Retrain Pipeline

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.10' }

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
      
          pip install pydantic==1.10.15
          pip install "dvc[gs]" --no-cache-dir
 
          pip install evidently==0.7.3 --no-deps
          pip install ujson nltk deprecation typing-inspect uuid6 numpy pandas scipy requests PyYAML jinja2 matplotlib plotly

          sed '/evidently/d' requirements.txt > req-clean.txt
          pip install -r req-clean.txt --no-cache-dir

      - name: Configure GCP auth
        env:
          GCP_B64: ${{ secrets.GCP_CREDENTIALS_B64 }}
        run: |
          echo "$GCP_B64" | base64 -d > gcp-key.json
          gcloud auth activate-service-account --key-file=gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/gcp-key.json" >> $GITHUB_ENV

          
      - name: Pull dataset from DVC
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
          echo "Using credentials: $GOOGLE_APPLICATION_CREDENTIALS"
          
          # âœ… FIX: Configure DVC to use the service account key
          dvc remote modify gcsremote credentialpath "$PWD/gcp-key.json" --local
      
          dvc pull -v

      - name: Data validation
        run: python scripts/data_validation.py

      - name: Train model
        run: python -m src.train --target target --problem_type classification --tune

      - name: Track model (DVC)
        run: |
          dvc add api/model/pipeline.pkl
          git add api/model/pipeline.pkl.dvc
          git commit -m "Auto-retrain: new model" || echo "No changes"
          dvc push -v
          git push origin main
